"""
Sandbox Module - Secure Code Execution Environment

This module provides a secure sandbox for executing Python code
generated by LLM agents. All data processing happens here, not
in the agents themselves.

Components:
- executor.py: Code execution in Docker containers
- security.py: Code safety validation
- docker_manager.py: Container lifecycle management
"""

from app.sandbox.executor import CodeExecutor
from app.sandbox.security import SecurityChecker

__all__ = ["CodeExecutor", "SecurityChecker"]